version: '3'

services:
  broker:
    image: greenbone/eulabeia-broker:latest
    networks:
      default:
        aliases:
          - broker
    restart: on-failure
  redis:
    image: greenbone/eulabeia-redis:latest
    volumes:
      - redis_socket_vol:/run/redis
  director:
    image: greenbone/eulabeia-director:latest
    depends_on:
      - broker
  sensor:
    image: greenbone/eulabeia-sensor:latest
    volumes:
      - redis_socket_vol:/run/redis
    depends_on:
      - director
      - redis
  example:
    image: greenbone/eulabeia-example-client:latest
    depends_on:
      - sensor
volumes:
  redis_socket_vol: {}
