version: '3'

services:
  broker:
    image: greenbone/eulabeia-broker:latest
    networks:
      default:
        aliases:
          - broker
    restart: on-failure
  director:
    image: greenbone/eulabeia-director:latest
    depends_on:
      - broker
  sensor:
    image: greenbone/eulabeia-sensor:latest
    depends_on:
      - director
  example:
    image: greenbone/eulabeia-example-client:latest
    depends_on:
      - sensor
