name: Smoke Test

on: [push, pull_request]

jobs:
  smoke-tests:
    name: "smoke-tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: make smoke-test
