name: Testing 

on: [push, pull_request]

jobs:
  unittests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go test ./... 
  smoke-tests:
    name: "smoke-tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: make smoke-test || ( printf "director logs:\n\n" && docker logs eulabeia_director &&  printf "sensor logs:\n\n" && docker logs eulabeia_sensor && make stop-container  && false)
